#!/usr/bin/env bash
# =============================================================================
# setup.sh — One-time Platform Setup & Cron Scheduling
# =============================================================================
# Run this ONCE on the controller node to:
#   1. Create required directories with correct permissions
#   2. Install dependencies on the controller
#   3. Validate servers.json
#   4. Set up SSH key directory structure
#   5. Install cron schedules for automated backups
#   6. Set up log rotation
#   7. Create the Oracle credential vault directory
# =============================================================================

set -Eeuo pipefail

PLATFORM_DIR="${1:-/opt/backup-platform}"
SCRIPTS_DIR="${PLATFORM_DIR}/scripts"
KEYS_DIR="${PLATFORM_DIR}/keys"
LOGS_DIR="${PLATFORM_DIR}/logs"
META_DIR="${PLATFORM_DIR}/metadata"
BACKUPS_DIR="${PLATFORM_DIR}/backups"
VAULT_DIR="/etc/bkp_vault"

COL_GREEN='\033[0;32m' COL_YELLOW='\033[0;33m' COL_RED='\033[0;31m' COL_RESET='\033[0m'
ok()   { echo -e "${COL_GREEN}[OK]${COL_RESET}   $*"; }
warn() { echo -e "${COL_YELLOW}[WARN]${COL_RESET} $*"; }
die()  { echo -e "${COL_RED}[ERR]${COL_RESET}  $*"; exit 1; }

echo "========================================"
echo " Backup Platform Setup"
echo " Platform dir: ${PLATFORM_DIR}"
echo "========================================"

# ---------------------------------------------------------------------------
# 1. Create directories
# ---------------------------------------------------------------------------
echo ""
echo "→ Creating directory structure..."
mkdir -p \
    "${SCRIPTS_DIR}" \
    "${KEYS_DIR}" \
    "${LOGS_DIR}" \
    "${META_DIR}" \
    "${BACKUPS_DIR}"

chmod 700 "${KEYS_DIR}"           # SSH keys — root only
chmod 755 "${PLATFORM_DIR}"
ok "Directories created."

# ---------------------------------------------------------------------------
# 2. Install controller dependencies
# ---------------------------------------------------------------------------
echo ""
echo "→ Installing controller dependencies..."
if command -v apt-get &>/dev/null; then
    apt-get update -qq
    apt-get install -y --no-install-recommends \
        openssh-client \
        rsync \
        jq \
        gpg \
        tar \
        curl \
        cron
    ok "Dependencies installed."
else
    warn "apt-get not found. Install manually: openssh-client rsync jq gpg tar curl"
fi

# ---------------------------------------------------------------------------
# 3. Validate servers.json
# ---------------------------------------------------------------------------
echo ""
echo "→ Validating servers.json..."
SERVERS_JSON="${PLATFORM_DIR}/servers.json"
[[ -f "${SERVERS_JSON}" ]] || die "servers.json not found at ${SERVERS_JSON}"
jq empty "${SERVERS_JSON}" || die "servers.json is invalid JSON."

SERVER_COUNT=$(jq '[.servers[] | select(.enabled==true)] | length' "${SERVERS_JSON}")
ok "servers.json valid. ${SERVER_COUNT} enabled server(s)."

# ---------------------------------------------------------------------------
# 4. SSH key check
# ---------------------------------------------------------------------------
echo ""
echo "→ Checking SSH keys..."
while IFS= read -r entry; do
    sid=$(echo "${entry}" | jq -r '.id')
    key=$(echo "${entry}" | jq -r '.ssh_key')
    if [[ -f "${key}" ]]; then
        chmod 600 "${key}"
        ok "Key found: ${sid} → ${key}"
    else
        warn "SSH key MISSING for ${sid}: ${key}"
        warn "  Place the private key at: ${key}"
    fi
done < <(jq -c '.servers[] | select(.enabled==true) | {id,ssh_key}' "${SERVERS_JSON}")

# ---------------------------------------------------------------------------
# 5. Oracle credential vault
# ---------------------------------------------------------------------------
echo ""
echo "→ Setting up Oracle credential vault..."
mkdir -p "${VAULT_DIR}"
chmod 700 "${VAULT_DIR}"
chown root:root "${VAULT_DIR}"

VAULT_FILE="${VAULT_DIR}/oracle_sys.pass"
if [[ ! -f "${VAULT_FILE}" ]]; then
    touch "${VAULT_FILE}"
    chmod 600 "${VAULT_FILE}"
    chown root:root "${VAULT_FILE}"
    warn "Oracle vault file created: ${VAULT_FILE}"
    warn "  Populate it with the Oracle SYS password:"
    warn "  echo 'YourSysPassword' > ${VAULT_FILE}"
    warn "  chmod 600 ${VAULT_FILE}"
else
    ok "Oracle vault exists: ${VAULT_FILE}"
fi

# ---------------------------------------------------------------------------
# 6. Install cron schedules
# ---------------------------------------------------------------------------
echo ""
echo "→ Installing cron schedules..."

CRON_FILE="/etc/cron.d/backup-platform"

cat > "${CRON_FILE}" <<CRON
# Backup Platform — Auto-generated by setup.sh
# Edit schedules here or update servers.json and re-run setup.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Daily backup: all enabled servers at 02:30 UTC
30 2 * * *   root   ${PLATFORM_DIR}/controller.sh backup --server all >> ${LOGS_DIR}/cron_backup.log 2>&1

# Weekly path discovery: Sundays at 01:00 UTC
0 1 * * 0    root   ${PLATFORM_DIR}/controller.sh discover --server all >> ${LOGS_DIR}/cron_discover.log 2>&1

# Daily status check: 07:00 UTC (for monitoring)
0 7 * * *    root   ${PLATFORM_DIR}/controller.sh status >> ${LOGS_DIR}/cron_status.log 2>&1
CRON

chmod 644 "${CRON_FILE}"
ok "Cron schedule installed: ${CRON_FILE}"

# ---------------------------------------------------------------------------
# 7. Log rotation
# ---------------------------------------------------------------------------
echo ""
echo "→ Setting up log rotation..."

LOGROTATE_FILE="/etc/logrotate.d/backup-platform"
cat > "${LOGROTATE_FILE}" <<LOGROTATE
${LOGS_DIR}/*.log {
    daily
    rotate 90
    compress
    delaycompress
    missingok
    notifempty
    create 640 root root
    sharedscripts
    postrotate
        # No service to signal — logs are written directly
        true
    endscript
}
LOGROTATE

chmod 644 "${LOGROTATE_FILE}"
ok "Log rotation configured: ${LOGROTATE_FILE}"

# ---------------------------------------------------------------------------
# 8. chmod scripts
# ---------------------------------------------------------------------------
echo ""
echo "→ Making scripts executable..."
chmod +x "${PLATFORM_DIR}/controller.sh" 2>/dev/null || true
for s in discover_paths.sh backup.sh restore.sh; do
    chmod +x "${SCRIPTS_DIR}/${s}" 2>/dev/null || true
done
ok "Scripts are executable."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "========================================"
ok "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Place SSH private keys in ${KEYS_DIR}/"
echo "  2. Set Oracle SYS password: echo 'pass' > ${VAULT_FILE}"
echo "  3. Test connectivity:    ${PLATFORM_DIR}/controller.sh status"
echo "  4. Run discovery:        ${PLATFORM_DIR}/controller.sh discover --server all"
echo "  5. Run first backup:     ${PLATFORM_DIR}/controller.sh backup --server all"
echo "========================================"
