/**
 * FIREBASE NOTIFICATION SYSTEM - CLEAN TABLE CREATION
 * 
 * This script DROPS and RECREATES notification tables from scratch
 * Database: Oracle XE (orclpdb)
 * 
 * OPERATIONS:
 * 1. Drops existing DEVICE_TOKEN table
 * 2. Drops existing NOTIFICATION_LOG table
 * 3. Creates fresh DEVICE_TOKEN table
 * 4. Creates fresh NOTIFICATION_LOG table
 * 5. Creates sequences and triggers
 * 6. Creates indexes
 * 
 * WARNING: This will delete all existing data in these tables!
 */

-- ============================================================================
-- STEP 1: DROP EXISTING TABLES (and all dependencies)
-- ============================================================================

DROP TABLE NOTIFICATION_PREFERENCES;
DROP TABLE NOTIFICATION_LOGS;
DROP TABLE DEVICE_TOKENS;
DROP SEQUENCE SEQ_DEVICE_TOKEN_ID;
DROP SEQUENCE SEQ_NOTIFICATION_LOG_ID;
DROP SEQUENCE SEQ_NOTIFICATION_PREFERENCE_ID;

-- ============================================================================
-- STEP 2: CREATE DEVICE_TOKENS TABLE
-- ============================================================================

CREATE TABLE DEVICE_TOKENS (
    ID                  NUMBER(19) PRIMARY KEY,
    TOKEN               VARCHAR2(500 CHAR) NOT NULL UNIQUE,
    USER_ID             NUMBER(19) NOT NULL,
    USER_TYPE           VARCHAR2(20 CHAR) NOT NULL,
    PLATFORM            VARCHAR2(20 CHAR) NOT NULL,
    DEVICE_NAME         VARCHAR2(255 CHAR),
    IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
    REGISTERED_AT       TIMESTAMP DEFAULT SYSDATE NOT NULL,
    LAST_USED_AT        TIMESTAMP,
    DEACTIVATED_AT      TIMESTAMP
);

COMMENT ON TABLE DEVICE_TOKENS IS 'Firebase Cloud Messaging device tokens for push notifications';
COMMENT ON COLUMN DEVICE_TOKENS.ID IS 'Unique device token ID (auto-generated)';
COMMENT ON COLUMN DEVICE_TOKENS.TOKEN IS 'Unique FCM device token from Firebase SDK';
COMMENT ON COLUMN DEVICE_TOKENS.USER_ID IS 'User ID who owns this device token (Patient, Doctor, or Admin ID)';
COMMENT ON COLUMN DEVICE_TOKENS.USER_TYPE IS 'Type of user: PATIENT, DOCTOR, or ADMIN';
COMMENT ON COLUMN DEVICE_TOKENS.PLATFORM IS 'Device platform: ANDROID, IOS, WEB, WINDOWS, MACOS';
COMMENT ON COLUMN DEVICE_TOKENS.DEVICE_NAME IS 'Human-readable device name (e.g., iPhone 13, Samsung Galaxy S21)';
COMMENT ON COLUMN DEVICE_TOKENS.IS_ACTIVE IS 'Whether token is currently active (1=yes, 0=no)';
COMMENT ON COLUMN DEVICE_TOKENS.REGISTERED_AT IS 'Timestamp when token was registered';
COMMENT ON COLUMN DEVICE_TOKENS.LAST_USED_AT IS 'Timestamp when token was last used';
COMMENT ON COLUMN DEVICE_TOKENS.DEACTIVATED_AT IS 'Timestamp when token was deactivated (soft delete)';

-- ============================================================================
-- STEP 3: CREATE NOTIFICATION_LOGS TABLE
-- ============================================================================

CREATE TABLE NOTIFICATION_LOGS (
    ID                      NUMBER(19) PRIMARY KEY,
    RECIPIENT_USER_ID       NUMBER(19) NOT NULL,
    RECIPIENT_USER_TYPE     VARCHAR2(20 CHAR) NOT NULL,
    TITLE                   VARCHAR2(255 CHAR) NOT NULL,
    BODY                    VARCHAR2(1000 CHAR) NOT NULL,
    NOTIFICATION_TYPE       VARCHAR2(50 CHAR) NOT NULL,
    RELATED_ENTITY_ID       NUMBER(19),
    RELATED_ENTITY_TYPE     VARCHAR2(50 CHAR),
    FCM_MESSAGE_ID          VARCHAR2(255 CHAR),
    DELIVERY_STATUS         VARCHAR2(20 CHAR) DEFAULT 'SENT' NOT NULL,
    IS_READ                 NUMBER(1) DEFAULT 0 NOT NULL,
    READ_AT                 TIMESTAMP,
    DATA_PAYLOAD            VARCHAR2(2000 CHAR),
    SENT_AT                 TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE NOTIFICATION_LOGS IS 'Audit trail of all notifications sent to users';
COMMENT ON COLUMN NOTIFICATION_LOGS.ID IS 'Unique notification log ID (auto-generated)';
COMMENT ON COLUMN NOTIFICATION_LOGS.RECIPIENT_USER_ID IS 'User ID who received the notification';
COMMENT ON COLUMN NOTIFICATION_LOGS.RECIPIENT_USER_TYPE IS 'Type of recipient: PATIENT, DOCTOR, ADMIN';
COMMENT ON COLUMN NOTIFICATION_LOGS.TITLE IS 'Notification title/subject';
COMMENT ON COLUMN NOTIFICATION_LOGS.BODY IS 'Notification message body';
COMMENT ON COLUMN NOTIFICATION_LOGS.NOTIFICATION_TYPE IS 'Notification type (APPOINTMENT_CONFIRMED, CANCELLED, REMINDER, etc.)';
COMMENT ON COLUMN NOTIFICATION_LOGS.RELATED_ENTITY_ID IS 'Related entity ID (e.g., Appointment ID, Request ID)';
COMMENT ON COLUMN NOTIFICATION_LOGS.RELATED_ENTITY_TYPE IS 'Type of related entity (APPOINTMENT, REQUEST, BOOKING, etc.)';
COMMENT ON COLUMN NOTIFICATION_LOGS.FCM_MESSAGE_ID IS 'FCM message ID for tracking delivery status';
COMMENT ON COLUMN NOTIFICATION_LOGS.DELIVERY_STATUS IS 'Delivery status (PENDING, SENT, DELIVERED, FAILED, BOUNCED, EXPIRED)';
COMMENT ON COLUMN NOTIFICATION_LOGS.IS_READ IS 'Whether user read notification (1=yes, 0=no)';
COMMENT ON COLUMN NOTIFICATION_LOGS.READ_AT IS 'Timestamp when user read the notification';
COMMENT ON COLUMN NOTIFICATION_LOGS.DATA_PAYLOAD IS 'Additional data payload in JSON format';
COMMENT ON COLUMN NOTIFICATION_LOGS.SENT_AT IS 'Timestamp when notification was sent';
COMMENT ON COLUMN NOTIFICATION_LOGS.CREATED_AT IS 'Timestamp when record was created';

-- ============================================================================
-- STEP 4: CREATE NOTIFICATION_PREFERENCES TABLE
-- ============================================================================

CREATE TABLE NOTIFICATION_PREFERENCES (
    ID                                      NUMBER(19) PRIMARY KEY,
    USER_ID                                 NUMBER(19) NOT NULL UNIQUE,
    USER_TYPE                               VARCHAR2(20 CHAR) NOT NULL,
    PUSH_NOTIFICATIONS_ENABLED              NUMBER(1) DEFAULT 1 NOT NULL,
    APPOINTMENT_CONFIRMED_ENABLED           NUMBER(1) DEFAULT 1 NOT NULL,
    APPOINTMENT_CANCELLED_ENABLED           NUMBER(1) DEFAULT 1 NOT NULL,
    APPOINTMENT_REMINDER_ENABLED            NUMBER(1) DEFAULT 1 NOT NULL,
    BOOKING_REQUEST_ENABLED                 NUMBER(1) DEFAULT 1 NOT NULL,
    SYSTEM_ANNOUNCEMENT_ENABLED             NUMBER(1) DEFAULT 1 NOT NULL,
    PROMOTIONAL_ENABLED                     NUMBER(1) DEFAULT 0 NOT NULL,
    QUIET_HOURS_START                       NUMBER(2),
    QUIET_HOURS_END                         NUMBER(2),
    ALLOW_NOTIFICATIONS_IN_QUIET_HOURS      NUMBER(1) DEFAULT 0 NOT NULL,
    LANGUAGE_PREFERENCE                     VARCHAR2(10 CHAR) DEFAULT 'en',
    EMAIL_NOTIFICATIONS_ENABLED             NUMBER(1) DEFAULT 0 NOT NULL,
    SMS_NOTIFICATIONS_ENABLED               NUMBER(1) DEFAULT 0 NOT NULL,
    DAILY_NOTIFICATION_LIMIT                NUMBER(3) DEFAULT 0,
    UPDATED_AT                              TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_AT                              TIMESTAMP DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE NOTIFICATION_PREFERENCES IS 'User preferences for receiving notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.ID IS 'Unique preference ID (auto-generated)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.USER_ID IS 'User ID (Patient, Doctor, or Admin)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.USER_TYPE IS 'Type of user: PATIENT, DOCTOR, ADMIN';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.PUSH_NOTIFICATIONS_ENABLED IS 'Whether push notifications are globally enabled';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.APPOINTMENT_CONFIRMED_ENABLED IS 'Enable appointment confirmation notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.APPOINTMENT_CANCELLED_ENABLED IS 'Enable appointment cancellation notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.APPOINTMENT_REMINDER_ENABLED IS 'Enable appointment reminder notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.BOOKING_REQUEST_ENABLED IS 'Enable booking request notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.SYSTEM_ANNOUNCEMENT_ENABLED IS 'Enable system announcement notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.PROMOTIONAL_ENABLED IS 'Enable promotional/marketing notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.QUIET_HOURS_START IS 'Start hour of quiet period (24-hour format, 0-23)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.QUIET_HOURS_END IS 'End hour of quiet period (24-hour format, 0-23)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.ALLOW_NOTIFICATIONS_IN_QUIET_HOURS IS 'Allow notifications during quiet hours';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.LANGUAGE_PREFERENCE IS 'Preferred language (e.g., en, ar)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.EMAIL_NOTIFICATIONS_ENABLED IS 'Enable email notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.SMS_NOTIFICATIONS_ENABLED IS 'Enable SMS notifications';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.DAILY_NOTIFICATION_LIMIT IS 'Max notifications per day (0 = unlimited)';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.UPDATED_AT IS 'Timestamp when preferences were last updated';
COMMENT ON COLUMN NOTIFICATION_PREFERENCES.CREATED_AT IS 'Timestamp when preferences were created';

CREATE SEQUENCE SEQ_DEVICE_TOKEN_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE SEQ_NOTIFICATION_LOG_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE SEQ_NOTIFICATION_PREFERENCE_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

-- ============================================================================
-- STEP 5: CREATE TRIGGERS FOR AUTO-INCREMENT
-- ============================================================================

CREATE OR REPLACE TRIGGER DEVICE_TOKEN_ID_TRIGGER
BEFORE INSERT ON DEVICE_TOKENS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_DEVICE_TOKEN_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    IF :NEW.REGISTERED_AT IS NULL THEN
        :NEW.REGISTERED_AT := SYSDATE;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NOTIFICATION_LOG_ID_TRIGGER
BEFORE INSERT ON NOTIFICATION_LOGS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_NOTIFICATION_LOG_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    IF :NEW.SENT_AT IS NULL THEN
        :NEW.SENT_AT := SYSDATE;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER NOTIFICATION_PREFERENCE_ID_TRIGGER
BEFORE INSERT ON NOTIFICATION_PREFERENCES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_NOTIFICATION_PREFERENCE_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER NOTIFICATION_PREFERENCE_UPDATE_TRIGGER
BEFORE UPDATE ON NOTIFICATION_PREFERENCES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/

-- ============================================================================
-- STEP 6: CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IDX_DEVICE_TOKEN_USER_ID ON DEVICE_TOKENS(USER_ID);
CREATE INDEX IDX_DEVICE_TOKEN_PLATFORM ON DEVICE_TOKENS(PLATFORM);
CREATE INDEX IDX_DEVICE_TOKEN_IS_ACTIVE ON DEVICE_TOKENS(IS_ACTIVE);

CREATE INDEX IDX_NOTIFICATION_LOG_RECIPIENT_USER ON NOTIFICATION_LOGS(RECIPIENT_USER_ID);
CREATE INDEX IDX_NOTIFICATION_LOG_IS_READ ON NOTIFICATION_LOGS(IS_READ);
CREATE INDEX IDX_NOTIFICATION_LOG_CREATED_AT ON NOTIFICATION_LOGS(CREATED_AT);
CREATE INDEX IDX_NOTIFICATION_LOG_UNREAD ON NOTIFICATION_LOGS(RECIPIENT_USER_ID, IS_READ);
CREATE INDEX IDX_NOTIFICATION_LOG_TYPE ON NOTIFICATION_LOGS(NOTIFICATION_TYPE);
CREATE INDEX IDX_NOTIFICATION_LOG_RELATED_ENTITY ON NOTIFICATION_LOGS(RELATED_ENTITY_ID, RELATED_ENTITY_TYPE);

CREATE INDEX IDX_NOTIFICATION_PREF_USER_ID ON NOTIFICATION_PREFERENCES(USER_ID);
CREATE INDEX IDX_NOTIFICATION_PREF_USER_TYPE ON NOTIFICATION_PREFERENCES(USER_TYPE);

-- ============================================================================
-- STEP 7: CREATE FOREIGN KEY CONSTRAINTS
-- ============================================================================

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DEVICE_TOKENS ADD CONSTRAINT FK_DEVICE_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES "user"(ID)';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('INFO: Foreign key FK_DEVICE_TOKEN_USER could not be created.');
    DBMS_OUTPUT.PUT_LINE('This is expected - will be added after Hibernate creates the "user" table.');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NOTIFICATION_LOGS ADD CONSTRAINT FK_NOTIFICATION_LOG_USER FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES "user"(ID)';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('INFO: Foreign key FK_NOTIFICATION_LOG_USER could not be created.');
    DBMS_OUTPUT.PUT_LINE('This is expected - will be added after Hibernate creates the "user" table.');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NOTIFICATION_PREFERENCES ADD CONSTRAINT FK_NOTIFICATION_PREF_USER FOREIGN KEY (USER_ID) REFERENCES "user"(ID)';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('INFO: Foreign key FK_NOTIFICATION_PREF_USER could not be created.');
    DBMS_OUTPUT.PUT_LINE('This is expected - will be added after Hibernate creates the "user" table.');
END;
/

-- ============================================================================
-- STEP 8: VERIFICATION
-- ============================================================================

PROMPT
PROMPT ╔════════════════════════════════════════════════════════════╗
PROMPT ║  FIREBASE NOTIFICATION TABLES CREATED SUCCESSFULLY         ║
PROMPT ╚════════════════════════════════════════════════════════════╝
PROMPT

PROMPT DEVICE_TOKENS table structure:
DESC DEVICE_TOKENS;

PROMPT
PROMPT NOTIFICATION_LOGS table structure:
DESC NOTIFICATION_LOGS;

PROMPT
PROMPT NOTIFICATION_PREFERENCES table structure:
DESC NOTIFICATION_PREFERENCES;

PROMPT
PROMPT Summary:
PROMPT ✓ DEVICE_TOKENS table created
PROMPT ✓ NOTIFICATION_LOGS table created
PROMPT ✓ NOTIFICATION_PREFERENCES table created
PROMPT ✓ Sequences created (SEQ_DEVICE_TOKEN_ID, SEQ_NOTIFICATION_LOG_ID, SEQ_NOTIFICATION_PREFERENCE_ID)
PROMPT ✓ Triggers created for auto-increment and timestamps
PROMPT ✓ Indexes created for optimal performance
PROMPT ✓ TOKEN column already has UNIQUE constraint (no separate index needed)
PROMPT ✓ USER_ID in NOTIFICATION_PREFERENCES has UNIQUE constraint (one per user)
PROMPT ✓ Foreign keys will be added after Hibernate creates "user" table
PROMPT

-- ============================================================================
-- END OF FIREBASE NOTIFICATION TABLES MIGRATION
-- ============================================================================
