name: CI - Build & Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  website-build:
    name: Build Thoutha website (Vite)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install & build (Thoutha-Website/ثوثة)
        run: |
          SITE_DIR="Thoutha-Website/ثوثة"
          if [ -f "$SITE_DIR/package.json" ]; then
            cd "$SITE_DIR"
            npm ci
            if npm run | sed -n '1,200p' | grep -q "build"; then
              npm run build
            else
              echo "No build script defined in package.json; skipping build"
            fi
            cd - || true
          else
            echo "No package.json in $SITE_DIR; skipping website build"
          fi
      - name: Upload built site artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: thoutha-dist
          path: Thoutha-Website/ثوثة/dist || Thoutha-Website/ثوثة/build || ''

  python-checks:
    name: Python - install & tests (Ai-chatbot)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python deps (Ai-chatbot/requirements.txt)
        run: |
          REQ=Ai-chatbot/requirements.txt
          if [ -f "$REQ" ]; then
            python -m pip install --upgrade pip
            pip install -r "$REQ"
          else
            echo "No Python requirements found at $REQ"
          fi
      - name: Run pytest if present
        run: |
          if [ -d "Ai-chatbot/tests" ] || ls Ai-chatbot/test* 1>/dev/null 2>&1; then
            pytest -q Ai-chatbot || exit 1
          else
            echo "No Python tests found"
          fi

  flutter-linux-build:
    name: Flutter (linux) - CMake build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake pkg-config
      - name: Configure & build flutter_moblie_app/linux if present
        run: |
          if [ -f "flutter_moblie_app/linux/CMakeLists.txt" ]; then
            mkdir -p flutter_moblie_app/linux/build
            cd flutter_moblie_app/linux/build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build . -- -j$(nproc)
          else
            echo "No CMakeLists.txt found for flutter_moblie_app/linux; skipping"
          fi

  shellcheck:
    name: ShellCheck - validate shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck on repo scripts
        run: |
          SCRIPTS=$(git ls-files '*.sh' || true)
          if [ -n "$SCRIPTS" ]; then
            shellcheck -x $SCRIPTS || exit 1
          else
            echo "No shell scripts to lint"
          fi
