name: Link Checker
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build site (if present)
        run: |
          SITE_DIR="Thoutha-Website/ثوثة"
          if [ -f "$SITE_DIR/package.json" ]; then
            cd "$SITE_DIR"
            npm ci
            if npm run | grep -q "build"; then
              npm run build
            fi
            cd - || true
          else
            echo "No JS site; skipping build"
          fi
      - name: Serve built site using preview script if present, else http-server (port 9000)
        run: |
          SITE_DIR="Thoutha-Website/ثوثة"
          DIST="$SITE_DIR/dist"
          cd "$SITE_DIR" || true
          if [ -f package.json ]; then
            if npm run | grep -q "preview"; then
              npm run preview -- --port 9000 &> /tmp/preview.log &
            else
              npm install -g http-server
              npx http-server "$DIST" -p 9000 > /tmp/http-server.log 2>&1 &
            fi
          else
            if [ -d "$DIST" ]; then
              npm install -g http-server
              npx http-server "$DIST" -p 9000 > /tmp/http-server.log 2>&1 &
            else
              echo "No package.json and no built dist; skipping serve"
            fi
          fi
          for i in $(seq 1 20); do
            if curl -sSf "http://localhost:9000" >/dev/null 2>&1; then
              echo "server up"
              break
            fi
            sleep 1
          done
      - name: Install lychee (link checker)
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/latest/download/lychee-linux-amd64.gz -o lychee.gz
          gunzip lychee.gz && chmod +x lychee && sudo mv lychee /usr/local/bin/lychee
      - name: Run lychee against the running preview
        run: |
          if curl -sSf "http://localhost:9000" >/dev/null 2>&1; then
            lychee http://localhost:9000 || exit 1
          else
            echo "No running site to scan; ensure build produced dist or adjust path"
          fi
